import Head from 'next/head'
import stacks from '@/data/stacks.json'
import { Stack, StackKey } from '@/interfaces/stack.interface'
import Link from 'next/link'
import Image from 'next/image'

export default function Home(): JSX.Element {
  const renderStacks = () => {
    return (Object.keys(stacks) as Array<keyof typeof stacks>).map(
      (stackKey: StackKey) => {
        const stack = stacks[stackKey]
        return (
          <Link
            key={stack.href}
            href={stack.href}
            className={`${stack.hoverClass} w-20 h-20 relative border-2 border-solid m-2 rounded-xl`}
          >
            <Image
              src={stack.logo}
              className='object-contain p-2'
              alt=''
              fill
            />
          </Link>
        )
      }
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-full flex justify-center items-center flex-col'>
        <div>What do you want to learn?</div>
        <div className='flex'>{renderStacks()}</div>
      </main>
    </>
  )
}
